### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by puchengy** [hubotio/hubot-redis-brain#38]
```
[Thu Nov 12 2020 20:30:08 GMT+0000 (UTC)] ERROR TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>:null:null)
    at Brain.robot.brain.on (/home/myhome/node_modules/hubot-redis-brain/src/redis-brain.js:93:42)
    at emitOne (events.js:116:13)
    at Brain.emit (events.js:211:7)
    at Brain.save (/home/myhome/node_modules/hubot/src/brain.coffee:54:6)
    at Timeout._onTimeout (/home/myhome/node_modules/hubot/src/brain.coffee:80:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```
Could you take a look? thanks!

**Comment by puchengy** [comment]
my bad, I did put some circular data in it
